appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a7302eb707003c0a1e
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: Y5n1Ntwe8y3mEPD6GIAlwo25Sb60Daz3zG4Uvd3K4ZpoUMsPnw2oRoH+CmzJQLJVcEatIdcAzXzUB+zxyHux51h+HLuTloYxkcGoohUwqRNhw72IWkBBeZgevaXz8QT5DQItSaKmwti7ewI1fdKwBtjqKu7nM7U9nDqGzQz1o7w0p2zkxa+Ilam3cEWwRPkvGDGnVfwM5yJwZXWx6SpzrAAzB/htIAe0xnZGx3YohOvz+XvCcimB0/7UbVfaUqb7Vx/W4eA9uGJp7JYMbWS2KNR911S43HIEpK0mWGNPqmDhALjB9GXXm4dFH+5a3dhOOqD6962iDZUVDb+mCsXpP4uXNR6Qzb93Fa1Lbw7KMW+6EqXr/m6Gft4I0GiXXITP29pwza8ocaIJUaFv5QacqjdmLrE73W3b9kTzFuJPXmDOb9G6ogcsv5hL8LpQGghtFfSudz+P9lvsqZGDkOkPEvTGXf51OASfzdzISE34/m71ck/JGLEKr/pHm/7PZ7BgKzXk9ZCQrVXPyrit5EuTsv3jatVkUW12hQK1l46D6HwYMzW5enh1TATl5eiYImctyriI1yNbymhmDX/HII6+p6NYcp9h3ZB6Wrv6QKQq+ll/b4IPgSQCfFDwXRg81GE2JIRNPlrmTd44AsoFDE/eJ3Q7pIfAf1LmpIfO0NlfNTM=}
